# Generated by Django 4.1 on 2022-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('canal', models.CharField(choices=[('Y', 'yandex'), ('O', 'ozon')], default='Y', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OzonNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YandexNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('tag', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
